export const aboutText = {
  intro1: "DREAM Consultancy Limited was established by a team of distinguished experts and professionals from diverse fields, united by a shared vision: to make meaningful contributions toward national advancement and societal betterment. With each professional boasting an esteemed reputation in their respective areas of expertise, DREAM Consultancy is positioned to deliver exceptional services that address pressing social, environmental, and economic challenges.",
  intro2: "Our theme slogan, “We Do for People and Society,” reflects our deep-rooted commitment to sustainable development and positive change. DREAM Consultancy provides specialized research, analysis, and consulting services that empower organizations, development partners, and government agencies to make informed decisions that benefit communities and drive progress.",
  mission: "Our mission is to design, develop, and implement innovative research and social survey initiatives that align with client needs and contribute to national growth. We are committed to empowering underserved communities by collaborating with public agencies and development partners to create sustainable solutions across critical sectors, including:\n• Livelihoods and income restoration\n• Environmental stewardship\n• Rehabilitation and resettlement\n• Gender equality\n• Nutrition, food security, and agricultural development\n• Youth empowerment and more.",
  vision: "DREAM Consultancy aspires to be a dynamic, market-leading research and consultancy firm, transforming our expertise and insights into impactful solutions tailored to the unique needs of our clients. We aim to become a trusted partner by providing top-tier consultancy services and fostering positive relationships with clients, stakeholders, and the wider society.",
  whatWeDo: "DREAM Consultancy offers a range of services to help organizations meet their goals and make lasting impacts. These include:\n\nResearch, Study and Survey\nConducting in-depth research, studies, and surveys across social, environmental, and climate change areas, as well as monitoring and evaluating project impacts.\n\nRehabilitation and Resettlement\nProviding socioeconomic studies and strategies for livelihoods restoration, resettlement planning, and compensation.\n\nMarket Linkages Development\nBuilding effective forward and backward linkages that prioritize the interests of primary producers and meet demands across market levels.\n\nInnovative Project Proposal Development\nCrafting project proposals that address socio-economic needs with a people-centered approach.",
  team: "Our team comprises highly skilled professionals with extensive experience in implementing development and research projects across multiple disciplines:\n\n• Social & Environmental Experts\n• Rehabilitation & Resettlement Experts\n• Research & Development Experts\n• Value Chain Experts\n• Disaster Management Experts\n• Gender Specialists\n• Monitoring, Evaluation, and Learning (MEL) Specialists\n• Natural Resource Management Experts\n• Enterprise Development Experts\n\nEach team member brings a unique perspective and proven expertise, ensuring that DREAM Consultancy delivers comprehensive and insightful solutions to our clients.",
  services: "We offer a diverse set of services tailored to the evolving needs of our clients and the broader development landscape:\n\n1. Data Collection & Analysis\nConducting baseline studies, mid-term evaluations, feasibility assessments, and more to provide actionable insights.\n2. Rehabilitation and Resettlement\nPerforming demographic surveys, preparing resettlement plans, and implementing land acquisition and compensation strategies.\n3. Research & Publication Support\nOffering report writing, manuscript development, data analysis, and research design and planning support for publication-quality outputs.\n4. Environmental Assessment\nConducting environmental monitoring, parameter testing, impact assessments, and developing comprehensive environmental management systems.\n5. Agro-Business Consultation\nSupporting the establishment of agro-industries, fisheries, poultry farms, and food processing units, as well as providing guidance on agricultural farming and trading.",
  dedication: "At DREAM Consultancy Limited, we believe in the power of knowledge and research to bring about sustainable development. By combining analytical rigor with a people-centered approach, we aim to be a partner of choice for those committed to creating a brighter, more resilient future.\n\nContact Us to learn how DREAM Consultancy Limited can support your organization’s vision and create meaningful impacts for people and society."
};
